title: Getting Started with GEDI Spaceborne Lidar for Ecosystem Applications
description: A Github page collecting foundational lidar educational materials and application examples with tutorials for exploration.
baseurl: "Explore_GEDI_EarthRISE_Training" # the subpath of your site, e.g. /blog
url: "https://servir.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/nasa-logo-web.png"

remote_theme: just-the-docs/just-the-docs
$body-background-color: $green-000
$text-color: $grey-dk-200; // Dark grey text
$link-color: $green-300;

# Aux links for the upper right navigation
aux_links:
  "NASA Earth Action":
    - "//appliedsciences.nasa.gov"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.

# Supports true (default) or false
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Github Page Template Copyright &copy; EarthRISE (NASA Marshall Space Flight Center) and University of Alabama in Huntsville"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
